server:
  port: 8080

spring:
  application:
    name: next502_backend

  profiles:
    active: bitc
    group:
      local:
        - h2
      bitc:
        - mysql

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 5

jwt:
  issuer: next502@bitc.ac.kr
  secret_key: next502-jwt-test-token-secret-key

