spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://58.239.58.243:3306/java402_team1_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: java402_team1
    password: java402_team1_!@#$

  sql:
    init:
      mode: always

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true